app/models.py
from . import db
from . import login_manager
from datetime import datetime
from flask import current_app
from flask_login import UserMixin
import hashlib
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import check_password_hash
from werkzeug.security import generate_password_hash


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id}).decode('utf-8')

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token.encode('utf-8'))
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id}).decode('utf-8')

    @staticmethod
    def reset_password(token, new_password):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token.encode('utf-8'))
        except:
            return False
        user = User.query.get(data.get('reset'))
        if user is None:
            return False
        user.password = new_password
        db.session.add(user)
        return True

    def __repr__(self):
        return '<User %r>' % self.username

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()

    def gravatar(self, size=100, default='identicon', rating='g'):
        url = 'https://secure.gravatar.com/avatar'
        hash = hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(url=url, hash=hash, size=size, default=default, rating=rating)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError
from ..models import Role, User


class NameForm(FlaskForm):
    name = StringField('What is your name gorgeous?', validators=[DataRequired()])
    submit = SubmitField('Submit')

class EditProfileForm(FlaskForm):
    name = StringField('Full Name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About Me')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_name):
    # creating an application instance (using WSGI)
    import pdb; pdb.set_trace()
    app = Flask(__name__)
    app.config.from_object(config['default'])
    config['default'].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import errors
from . import views

app/main/views.py
from flask import flash
from flask import render_template
from flask import session
from flask import redirect
from flask import url_for
from flask import current_app
from flask_login import login_required
from flask_login import current_user
from .. import db
from ..models import User
from ..email import send_email
from . import main
from .forms import NameForm, EditProfileForm


@main.route('/', methods=['GET', 'POST'])
def index():
    form = NameForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.name.data).first()
        if user is None:
            user = User(username=form.name.data)
            db.session.add(user)
            db.session.commit()
            session['known'] = False
            if current_app.config['FLASKY_ADMIN']:
                send_email(current_app.config['FLASKY_ADMIN'], 'New User',
                           'mail/new_user', user=user)
        else:
            session['known'] = True
        session['name'] = form.name.data
        return redirect(url_for('.index'))
    return render_template('index.html',
                           form=form, name=session.get('name'),
                           known=session.get('known', False))

@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}BuddySystem{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<style>
        body {
        height: 500px;
        background-color: #1c87c9; /* For browsers that do not support gradients */
        background-image: linear-gradient(to right, #a8c6d2, #1c87c9, #bbddea);
        }
      </style>

<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://www.youtube.com/watch?v=39xq5AATMp4"><img src="https://i.imgur.com/MPUnZUm.jpg" alt="Buddy System Image" height="20" width="20"></a>
            <a class="navbar-brand" href="{{ url_for('main.index') }}" style = "font-family:Arial, Helvetica, sans-serif;color:whitesmoke;font-weight:bold;font-size:24px;">BuddySystem</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}" style = "font-family:Arial, Helvetica, sans-serif;font-size:16px;color:gray;">Home</a></li>
                <li><a href="{{ url_for('auth.about') }}" style = "font-family:Arial, Helvetica, sans-serif;font-size:16px;color:gray;">About</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}" style = "font-family:Arial, Helvetica, sans-serif;font-size:16px;color:gray;">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style = "font-family:Arial, Helvetica, sans-serif;font-size:16px;color:gray;">Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('main.edit_profile') }}" style = "font-family:Arial, Helvetica, sans-serif;font-size:16px;color:black;">Edit Profile</a></li>
                        <li><a href="{{ url_for('auth.logout') }}" style = "font-family:Arial, Helvetica, sans-serif;font-size:16px;color:black;">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuddySystem - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}BuddySystem{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1 style = "font-family:Noto Sans, sans-serif;color:whitesmoke;font-weight:bold;font-size:40px;" align="center">{% if current_user.is_authenticated %}Hello {{ current_user.username }}!{% else %}{% endif %}</h1></br>
        <a href="https://www.youtube.com/watch?v=gtdnMWMWN3o"><img src="https://i.imgur.com/MPUnZUm.jpg" alt="Buddy System Image" height="224" width="224"></a>
        <a href="https://www.youtube.com/watch?v=Thb0NHX7jc8&feature=youtu.be"><img src="https://i.imgur.com/MPUnZUm.jpg" alt="Buddy System Image" height="224" width="224"></a>
        <a href="https://www.youtube.com/watch?v=9yZNAf-aCd0"><img src="https://i.imgur.com/MPUnZUm.jpg" alt="Buddy System Image" height="224" width="224"></a>
        <a href="https://www.youtube.com/watch?v=82C-XG5lElk"><img src="https://i.imgur.com/MPUnZUm.jpg" alt="Buddy System Image" height="224" width="224"></a>
        <a href="https://www.youtube.com/watch?v=8BjthoKHXEo"><img src="https://i.imgur.com/MPUnZUm.jpg" alt="Buddy System Image" height="224" width="224"></a>
    <h2 style="color: whitesmoke;font-family:Noto Sans, sans-serif;font-weight:bold;font-size:65px" align="center">BuddySystem</h2></br>
    <p style="color: black;font-family:Noto Sans, sans-serif;font-size:16px;font-style: italic;" align="center">Walk safe and make a Buddy along the way!</p></div>
</div>
<p align="center" style = "font-family:Noto Sans, sans-serif;font-size:21px;font-style:italic;color:whitesmoke;">
    We are all aware of the age old addage "There is safety in numbers." </br>
    BuddySystem is a social betterment app; with the help of BuddySystem you will be able </br>
    to meet a walking Buddy and safely walk from place to place and ensure you're not alone. </br>
    BuddySystem can appeal to ALL ages and sexes.</br>
    Whether you are trying to meet someone who may work at your same company for a regular walking Buddy</br>
    to work, a retired socialite looking for company in afternoon walks, or a late night</br>
    bar goer looking for a safe walk home a couple of blocks away,</br>
    BuddySystem can be used to better your walking experience no matter what walk of life.</p>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block title %}BuddySystem - {{ user.username }}{% endblock %}

{% block page_content %}
        <div class="page-header">
            <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">
            <div class="profile-header">
                <h1 style = "font-family:Noto Sans, sans-serif;color:whitesmoke;font-weight:bold;font-size:45px;">{{ user.username }}</h1>
    {% if user.name or user.location %}</br>
    <p style = "font-family:Noto Sans, sans-serif;font-size:21px;color:black;">
        {% if user.name %}{{ user.name }}{% endif %}
        {% if user.location %}
            from <a href="http://maps.google.com/?q={{ user.location }}" style="color:rgb(36, 86, 194)">{{ user.location }}</a>
        {% endif %}
    </p>
    {% endif %}
    {% if user.about_me %}<p style = "font-family:Noto Sans, sans-serif;font-size:21px;color:black;">{{ user.about_me }}</p>{% endif %}
    <p style = "font-family:Noto Sans, sans-serif;font-size:16px;color:black;font-style:italic;">Member since {{ moment(user.member_since).format('L') }}. </br>
      Last seen {{ moment(user.last_seen).fromNow() }}.</p>
  </div>
</div>
{% endblock %}